services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app           
      - /app/node_modules  

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app